module.exports = {
  source: ['tokens/theme-transformed.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`Do not edit directly, this file was auto-generated`];
    },
  },
  platforms: {
    web: {
      buildPath: 'tokens/',
      files: [
        {
          destination: 'theme.json',
          format: 'json/nested',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
  },
};
